### ISSUE TITLE
Add the template for backend

### ISSUE THREAD

**Issue by hello-work** [hello-work/e-commerce#1]
use the node with express

**Comment by devendra-dantal04** [comment]
can you assign these issue to me I want to work on it

**Comment by hello-work** [comment]
> can you assign these issue to me I want to work on it

Assigned

**Comment by devendra-dantal04** [comment]
Pls review my PR.

**Comment by devendra-dantal04** [comment]
can I need to do a second PR for the changes you said?

**Comment by hello-work** [comment]
> can I need to do a second PR for the changes you said?

No its fine I can create a issue for that for another person

**Comment by devendra-dantal04** [comment]
> > can I need to do a second PR for the changes you said?
> 
> No its fine I can create a issue for that for another person

ok and thank you @hello-work

**Comment by hello-work** [comment]
Issue closed with #12
