### ISSUE TITLE
Database connection

### ISSUE THREAD

**Issue by VighneshManjrekar** [hello-work/e-commerce#10]
What database you are willing to use for this project
If you are going to use mongo I can add database connection for mongo database

**Comment by hello-work** [comment]
> What database you are willing to use for this project If you are going to use mongo I can add database connection for mongo database

Yes plan to add mongoose in here.

**Comment by VighneshManjrekar** [comment]
Kindly assign me this issue I can work on it

**Comment by hello-work** [comment]
> Kindly assign me this issue I can work on it

Done.

**Comment by hello-work** [comment]
@VighneshManjrekar can you please also rename the modules as controllers and db folder as module.
